class ScadFile:
    def __init__(self, target, fn = None):
        """target can be an Object or an ScadObject (in fact, anything with a
        to_scad method)."""

        self._scad = target.to_scad()
        self._fn = fn

    def to_code(self):
        header_lines = [
            "// This file was auto-generated by cadlib",
        ]

        if self._fn is not None:
            header_lines += [
                "$fn = {};".format(self._fn),
            ]

        header_code = "\n".join(header_lines) + "\n\n"
        body_code = self._scad.to_code()

        # End with a newline
        return header_code + body_code + "\n"

    def write(self, file_name):
        with open(file_name, "w", encoding='utf-8') as file:
            file.write(self.to_code())
